# Generated by Django 4.0 on 2021-12-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
