# Generated by Django 4.0 on 2021-12-19 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(19)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_team.team')),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
    ]
